# Generated by Django 3.2 on 2021-05-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210504_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='classcode',
        ),
    ]
