# Generated by Django 3.2 on 2021-05-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_students_classcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='confirmPassword',
            new_name='confirmpassword',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='lastName',
            new_name='lastname',
        ),
    ]
