# Generated by Django 3.2 on 2021-05-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('userName', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('firstName', models.CharField(max_length=300)),
                ('lastName', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('confirmPassword', models.CharField(max_length=300)),
            ],
        ),
    ]
