# Generated by Django 3.2 on 2021-05-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20210512_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='image',
        ),
    ]
