# Generated by Django 3.2 on 2021-05-10 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignmentid', models.IntegerField(primary_key=True, serialize=False)),
                ('classcodeid', models.CharField(max_length=30)),
                ('assignmentfile', models.FileField(upload_to='')),
                ('assignmenttitle', models.CharField(blank=True, max_length=100)),
                ('listAssignment', models.TextField(blank=True)),
                ('assignmentgivendate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('assignmentsubmissindate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
