# Generated by Django 3.2 on 2021-05-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assignmentfile',
            new_name='assignmentFile',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='assignmentgivendate',
            new_name='assignmentGivenDate',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='assignmentsubmissindate',
            new_name='assignmentSubmissinDate',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='assignmenttitle',
            new_name='assignmentTitle',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='assignmentid',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='classcodeid',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='listAssignment',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignmentId',
            field=models.CharField(default=0, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
