# Generated by Django 3.2 on 2021-05-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20210512_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assignmentFile',
            new_name='assignmentfile',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='assignmentGivenDate',
            new_name='assignmentgivendate',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='assignmentId',
            new_name='assignmentid',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='assignmentSubmissinDate',
            new_name='assignmentsubmissindate',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='assignmentTitle',
            new_name='assignmenttitle',
        ),
    ]
