# Generated by Django 3.2 on 2021-05-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taclass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taclass',
            name='id',
        ),
        migrations.AlterField(
            model_name='taclass',
            name='classCode',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
