# Generated by Django 3.2 on 2021-05-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taclass', '0005_auto_20210512_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taclass',
            old_name='classImage',
            new_name='classimage',
        ),
        migrations.RenameField(
            model_name='taclass',
            old_name='classLink',
            new_name='classlink',
        ),
        migrations.RenameField(
            model_name='taclass',
            old_name='className',
            new_name='classname',
        ),
        migrations.RenameField(
            model_name='taclass',
            old_name='classTime',
            new_name='classtime',
        ),
        migrations.RenameField(
            model_name='taclass',
            old_name='teacherName',
            new_name='teachername',
        ),
    ]
