# Generated by Django 3.2 on 2021-05-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taclass', '0006_auto_20210512_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taclass',
            name='classlink',
        ),
        migrations.RemoveField(
            model_name='taclass',
            name='classtime',
        ),
    ]
